default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: postgres
  host: localhost
  database: vale_desconto_development

production:
  <<: *default
  database: vale_desconto_production
  username: vale_desconto
  password: <%= ENV['MY_APP_RENDER_DATABASE_PASSWORD'] %>
